feat: Document Loader for Datastore.
googleapis/langchain-google-datastore-python pull request #7
Opened 2024-02-14 05:22 UTC by JU-2094

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/langchain-google-datastore-python/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [X] Appropriate docs were updated (if necessary)

Add Document Loader for Firestore in Datastore Mode

2024-02-15 18:01 UTC, pl04351820 commented on src/langchain_google_datastore/utility/document_converter.py
> +            if (l == 1) and ("key" in val) and isinstance(val["key"], tuple):
Do we want to store the data with different value type? The unified data seems clearer to me.

2024-02-15 18:16 UTC, JU-2094 commented on src/langchain_google_datastore/document_loader.py
> +            client: Client for interacting with the Google Cloud Firestore API.
Changed

2024-02-15 18:30 UTC, JU-2094 commented on src/langchain_google_datastore/utility/document_converter.py
> +            if (l == 1) and ("key" in val) and isinstance(val["key"], tuple):
Discussed offline, will add a `datastore_type` to make the conversion clear

2024-02-16 04:02 UTC, kurtisvg requested changes

2024-02-16 04:02 UTC, kurtisvg commented on src/tests/unit_tests/test_document_loader.py
> +    return TestCase()
What is this being used for?

2024-02-16 04:02 UTC, kurtisvg commented on src/langchain_google_datastore/document_loader.py
> +                    continue
Could we add some comments around this section.

Why do we continue if theirs no key? should we error instead?

2024-02-16 15:50 UTC, JU-2094 commented on src/tests/unit_tests/test_document_loader.py
> +    return TestCase()
For the assert,  that ensures two list have the same elements. The name in python3 is misleading:

test_case.assertCountEqual

https://docs.python.org/3.6/library/unittest.html#unittest.TestCase.assertCountEqual

Previously called assertItemsEqual

2024-02-16 15:55 UTC, JU-2094 commented on src/langchain_google_datastore/document_loader.py
> +                    continue
I was skipping in case key was not present something like a list of empty strings e.g. instead of failing the whole batch. 
I'm ok with raising an error as well. I'll change to that if you prefer

2024-02-16 16:00 UTC, JU-2094 commented on src/langchain_google_datastore/utility/document_converter.py
> +            ]
SG. I will move this to the TOP in both PRs

2024-02-16 16:06 UTC, JU-2094 commented on src/langchain_google_datastore/utility/document_converter.py
> +                val_converted = entity
That assumes no corruption? I have all those conditionals to ensure it has the attributes. I can change it to that way
and blame the user if it crashes I suppose

2024-02-16 20:24 UTC, kurtisvg approved these changes

2024-02-16 20:24 UTC, kurtisvg commented on src/langchain_google_datastore/document_converter.py
> +class TypeEnum(StrEnum):
nit: remove enum

2024-02-16 20:24 UTC, kurtisvg commented on src/langchain_google_datastore/document_converter.py
> +    doc = Document(page_content=str(page_content), metadata=metadata)
json here as well

2024-02-16 20:24 UTC, kurtisvg commented on src/langchain_google_datastore/document_loader.py
> +            client: Client for interacting with the Google Cloud Firestore API.
nit: clarify client type

2024-02-16 20:24 UTC, kurtisvg commented on src/langchain_google_datastore/document_loader.py
> +                ):
nit: try to shorten

2024-02-16 23:15 UTC, merged